### ISSUE TITLE
Is there a way to specify ordering in /resources API

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#1]
One of the use cases to /resource API is fetch the List of books available/uploaded. The default ordering is ascending i.e Books uploaded first are fetched first and then books uploaded later come next.
Is there a way to specify the ordering; I would like to fetch the most recently uploaded books first.

**Comment by damooo** [comment]
we can use sort_doc parameter for that anna.
like [["created", -1]]
it is array of two element arrays, where each two element array contains a key in document, "created", whatever, and second element is order, 1 or -1. such two element arrays can be specified many in main array. i.e if two objs ranked same in first element sort, they will then get ranked according to second field's specified order.

**Comment by damooo** [comment]
It is just analogous to mongodb notation here https://stackoverflow.com/questions/8109122/how-to-sort-mongodb-with-pymongo

**Comment by shashikiranraifox** [comment]
> we can use sort_doc parameter for that anna.
> like [["created", -1]]
> it is array of two element arrays, where each two element array contains a key in document, "created", whatever, and second element is order, 1 or -1. such two element arrays can be specified many in main array. i.e if two objs ranked same in first element sort, they will then get ranked according to second field's specified order.

Noted. Will try and revert.

**Comment by shashikiranraifox** [comment]
Seems to be working. You can close it
@damooo
