### ISSUE TITLE
Blocker: Pagination API support not effecient

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#10]
If we pass return_count = true along with the GET request to fetch a list of objects[I tried with users], the response contains only the total count and nothing else as follow:

**API Call: https://apps.vedavaapi.org/stage/api/accounts/agents/v1/users?return_count=true
{count: 4}**

This is not at all efficient. We have to make two API calls, one to fetch count and another to fetch the list of objects 

Expected Result: The API response should contain the actual response and in addition it should also contain the total count of objects.
This fix should go to wherever we are using return_count = true

**Comment by shashikiranraifox** [comment]
@damooo  @sai-r-susarla  Please notify me when the support for this is added.

**Comment by damooo** [comment]
'll be done by tomarrow

**Comment by damooo** [comment]
now it is added at https://apps.vedavaapi.org/dev/api now any list response will come in a wrapper, containing totla count and `items`.
