### ISSUE TITLE
GET  teams API should list only the teams that user is part of

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#11]
Will explain the Issue using an example
1. We have a Team for Root Admins
2. A Root Admin user when he logs in and fetched the teams, he gets all the teams as part of response including the Root Admins teams which is correct.
3. I now logged in as a normal user[user who is not part of Root Admins group]. The GET teams API returns  all the teams including Root Admins.
4. I have to then check the members array to really confirm the logged in User is part of the team or not.

Suggested Improvement: If a User is not a part of Team, the GET teams API should not send the teams of which the user is not part of

**Comment by damooo** [comment]
if we want to get those teams in which he is explicit member, we can filter with
```json
{
  "members": <user_id>
}
```
i.e those teams in which he is `explicitly` listed. but not that team's parent teams.
but effectively user is member of parent teams also.

above /teams is teams query endpoint, irrespecive of he is member or not.
for teams of that user/any user; there are `/me/teams` and `/users/<user_id>/teams` endpoints.. with  but pagination not possible there now. will add pagination for those endpoints too. and an option to choose explicitly added teems also.

**Comment by shashikiranraifox** [comment]
@damooo  Any one of /me/teams and /users/<user_id>/teams with proper pagination [and Permissions] would suffice our needs. 

**Please note that the response format should be the same as GET /teams.** 

The problem with using filtering from the generic GET /teams API is that our pagination will not be accurate. Ex: Filtering out 2 entries from a page of 10 will show only 8 when the page should actually shown 10.

**Comment by damooo** [comment]
filtering, i mean through api anna, not client side filtering.
there is selector_doc in GET `/teams` api.

**Comment by shashikiranraifox** [comment]
This filtering worked. You can close the issue now or when you provide the other APIs you had mentioned.
