### ISSUE TITLE
Permissions cannot be granted to Users over a Team

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#14]
I used the POST /resources/{resource_id}/agents API call to grant "delete" and "updateLinks" permission to a user over a team.  Here the resource Id is the team identifier.
I got a 404 response.
So basically the above method only works with resources but cannot be used to grant a user permissions over a team.[As of now team is not a resource I assume because of this behavior] 

**If the API is not meant to be used to provide users permissions over a team, then we cannot implement the feature of granting or revoking permissions to Users[Over a team or other Users]. Is there an alternate API to perform the above task??**

**Or should the feature of providing users permissions over a team or other users  not be present ?**

Below are details of the Request:

Request URL[5cc2e65f9218e60008338c9c is the team identifier]

https://apps.vedavaapi.org/stage/api/objstore/v1/resources/5cc2e65f9218e60008338c9c/agents

Form Data:

agents_set_name: granted
actions: ["updateLinks","delete"]
user_ids: ["5cbeb6fb9218e60008338c7e"]
team_ids: []

Method: {"code":404,"message":"resource not found"}

**Comment by damooo** [comment]
users and teams api is differant from objstore.
in `accounts/agents` api, in `default` namespace `accounts/agents/<agent_id>/agents` api.

**Comment by shashikiranraifox** [comment]
If API support is provided for the feature mentioned in this Issue, then we shall implement the same. Else we can close the issue if there is consensus if the feature[Users getting permissions over teams or others] itself is not required.

@sai-r-susarla Feel free to have a look at the issue description and share your feedback

**Comment by damooo** [comment]
the above mentioned api addresses this anna.

**Comment by shashikiranraifox** [comment]
Noticed the API endpoints you had mentioned. We shall implement Assign Permissions the with the API mentioned.
