### ISSUE TITLE
[Critical] Permissions are granted by default

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#18]
Login as Root Admin

1. Create a New Users
2. Create a New team
3. Add the User to the newly created team
4. The User has all the Permissions granted to him by default.
i.e he can delete, updatePermissions, Add or Remove members[updateContent] from the Team.

Expected Result: A Newly added user to a Team should have any permissions granted to him. He should be able only view the team. Only after Team admin grants him permissions, he should be able to perform corresponding actions

**Comment by damooo** [comment]
It should not be the case anna.. may be i set wrong default perms in new version. will check and revert.

**Comment by sai-r-susarla** [comment]
A subteam inherits the permissions of its parent team. So members of a subteam also inherit privileges of its parent team. The parent team in this case happens to be the root admin team. Hence the issue.
