### ISSUE TITLE
[Blocker] Unable to Fetch Teams for a normal[not root admin] user - 500 Internal Server Error

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#19]
1. Logged in as Root Admin
2. Created Two Teams as child and grand child of ALL_USERS_TEAM
3. Added a member[vvuser1@gmail.com] to the newly created grand child team.
4. Logout and Login as vvuser1@gmail.com. 
Actual Result: No teams are shown due to an Internal Server Error

Request Details:

Request URL: https://apps.vedavaapi.org/prod/api/accounts/v1/teams?selector_doc=%7B%22members%22:%20%225cd94efde2b0c10009c7711c%22%7D&sort_doc=%5B%5B%22created%22,%20-1%5D%5D&start=0&count=15

Query Parameters:

selector_doc: {"members": "5cd94efde2b0c10009c7711c"}
sort_doc: [["created", -1]]
start: 0
count: 15

Server: https://apps.vedavaapi.org/prod/api

**Comment by damooo** [comment]
fixed anna.
