### ISSUE TITLE
Supporting APIs for Sequence Annotations

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#2]
Please share the documentation on following APIs:

1. API to Create a Sequence Annotation
2. API to Edit a Sequence Annotation.
3. API to Delete a Sequence Annotation.
4. API to get 'Concatenated content' within the region of Sequence Annotation[Please refer the user story on Trello]
5. API to fetch the list of only Sequence Annotations.
Please note that you would have to support the following ordering "Left to right", "Right to left" and "Created at" for 1,2 and 4

If you want to share the documentation/information via Video recording, please feel free to do so. I would recommend using loom which has Chrome Plugin and is free. 

Link: https://www.useloom.com/

**Comment by damooo** [comment]
here is schema of sequence annotation
https://api.vedavaapi.org/py/demo/objstore/v1/schemas/SequenceAnnotation

it's notable fields are, "members", "aggrContentGenerator", "orderingName", "target".
```
{
  "jsonClass": "SequenceAnnotation",
  "target": "563bvrd563ve563v35dsv376b33",
  "members": {
    "jsonClass": "WrapperObject",
    "0": "5cuwhdk25b2432b376399037123",
    "1": "54378bv35v24c2i82b262j2v282b2",
    "3": "57vtyrn27335v35vc34sne9smks72"
  },
  "aggrContentGenerator": {
    "delimiter": "-"
  },
  "orderingName": "top-to-bottom left-to-right"
}
```
### members
it is dictionary, where key denotes index of a member in this sequence, and value is _id of the member. this allows index keys to be skipped, or placeholders to be kept, or any string can be used to index.

### aggrContentGenerator
it specifies any options, on how we can generate aggregate from this sequence. presently only delimiter specified in it's definition, denotes, with which we have to delimiter these all sequence items, to get the aggregated content.
`
"aggrContentGenerator": {
  "delimiter": "-"
}
`
### orderingName
name of ordering of sequnce if any. i.e if intended purpose of sequence has notion of ordering too, we specify that orderingName here like 'left-to-right', 'ascending', 'descending' etc, can be multiple seperated by space.

### target
target is_id of  resource which we targetting. like _id of page, etc.

**Comment by shashikiranraifox** [comment]
Thank you for the schema, it would be definitely helpful for us. However we more information. Can you please specify the exact API routes along with required parameters for the 5 APIs mentioned in the issue.

**Comment by damooo** [comment]
1. creating sequence annotation, is client's job. just like while posting a new book, we create it's book json, and post it through `/resources` `POST`. we have to create above structure.
2. EDITING is same again, POST with `_id` field set.
3. `/resources` `DELETE` endpoint with array containing sequence annotation _id
4. from sequence annotation object, we on client side compute concatenated text, by joining all member strings with delimiter.
5. filter will be `{"jsonClass": "SequenceAnnotation", "target": target_page_id}`

**Comment by damooo** [comment]
for step1, to create Sequencennotation, too we just get AnnotationList from adapter, and will order them in required order, thus we will create sequence annotation. if you can provide how you are distinguishing SequenceAnnotation, at the time of invoking adapter in mirador's Annotation implementation, i can write a function to generate this structure based on it.

**Comment by shashikiranraifox** [comment]
Just highlighting my requirement in Bold. 
I need to get all the Shape Annotations within a **Region** or **Boundary** 
For Example, User may choose to draw a region around only 1 paragraph and the the page may consist of many paragraphs. 
**We need an API to get all the Shape Annotations within the Paragraph or within the Boundaries of Paragraph**

**Comment by shashikiranraifox** [comment]
Will share the screenshots here and also update the story on Trello so that you can see the UI for creating Sequence Annotations.

**Comment by damooo** [comment]
let's say adapter.AnnotationsList is all shape annotations on this page. we do filter over that array, to chose those annotations, which are inside in selected region by comparing their xywh, and their jsonClass.

**Comment by shashikiranraifox** [comment]
> let's say adapter.AnnotationsList is all shape annotations on this page. we do filter over that array, to chose those annotations, which are inside in selected region by comparing their xywh, and their jsonClass.

This is not an efficient approach. There could be 1000+ annotations on a page. Let me know your decision. Based on the decision we shall fix on one approach: either we shall use the API if provided or compare and extract from the list of all annotations.

CC: @sai-r-susarla

**Comment by shashikiranraifox** [comment]
> Will share the screenshots here and also update the story on Trello so that you can see the UI for creating Sequence Annotations.

Attached are the Screenshots of the UI and Pop-up used for Sequence Annotations.

![screenshot 27](https://user-images.githubusercontent.com/45028441/52198903-682eb480-288a-11e9-8f64-7e744a10b90c.png)
![screenshot 28](https://user-images.githubusercontent.com/45028441/52198905-682eb480-288a-11e9-963d-ba042e7b00e7.png)

**Comment by shashikiranraifox** [comment]
> > This is not an efficient approach. There could be 1000+ annotations on a page.
> 
> yes. it seems. but if a person select a large section over those 1000 annotations, then we have to transfer all those annotations again, though we have them on client. which among these two can be frequent, and main usage?
> 
> that ui, i already have on my local machine, just how it invokes endpoint's create method is, i.e what details it will send to endpoint to distinguish. i am checking that.

My views are that one would not create a sequence of 1000 shape annotations. However you have raised a valid query, please do check with @sai-r-susarla . Based on the frequency/usage you can decide to provide an API or not.

**Comment by shashikiranraifox** [comment]
> > This is not an efficient approach. There could be 1000+ annotations on a page.
> 
> yes. it seems. but if a person select a large section over those 1000 annotations, then we have to transfer all those annotations again, though we have them on client. which among these two can be frequent, and main usage?
> 
> that ui, i already have on my local machine, just how it invokes endpoint's create method is, i.e what details it will send to endpoint to distinguish. i am checking that.

@damooo  Please note that we are just providing the UI for sequence annotations. We have not yet  implemented the functionality to create/edit sequence annotations. That is to be done in this sprint. Henceforth we  raised the current query on github.

**Comment by shashikiranraifox** [comment]
> 1. creating sequence annotation, is client side work. just like while posting a new book, we create it's book json, and post it through `/resources` `POST`. we have to create above structure.
> 2. EDITING is same again, POST with `_id` field set.
> 3. `/resources` `DELETE` endpoint with array containing sequence annotation _id
> 4. from sequence annotation object, we on client side compute concatenated text, by joining all member strings with delimiter.
> 5. filter will be `{"jsonClass": "SequenceAnnotation", "target": target_page_id}`

@damooo  In the Scheme **orderingName** can either be top-to-bottom or left-to-right. Are these the only ordering supported or are there any plans to support right-to-left, bottom-to-top ?

**Comment by damooo** [comment]
they are just hints/labels anna, we can add what ever we want. actual ordering is taken care by indexes in 'members' dict as in above example dict.

**Comment by damooo** [comment]
it seems good to retrieve from server only, as we can retrieve with projection itself. there is no new api needed, but just selector_doc will contain those restrictions. and at the time of creation of a annotation, we just have to expand selector to allow such querying, i will add this, and come back to you within 15 ms.

**Comment by shashikiranraifox** [comment]
> they are just hints/labels anna, we can add what ever we want. actual ordering is taken care by indexes in 'members' dict as in above example dict.

Noted. Thanks.

**Comment by shashikiranraifox** [comment]
Based on the discussion here, I infer that it would not be possible provide an API for 4.[ API to get 'Concatenated content' within the region of Sequence Annotation[Please refer the user story on Trello]

@damooo  Please confirm so that I shall go ahead and make changes on client itself for 4.

**Comment by damooo** [comment]
Yes anna. otherwise we have to give special treatment on server for them. hence, we just have to get all annotations in bounding box on client side itself by a filter fn, and concatenate them with delimiter.

**Comment by damooo** [comment]
@shashikiranraifox we can pass a js function string, with which we want to filter those rectangle anna. like, now filter_doc will be:
```
{"$where":"function() {  if(!this.selector || !this.selector.default || !this.selector.default.rectangle) {  return false;  }  let rectangle = this.selector.default.rectangle;  if((rectangle.x < 200) || (rectangle.y < 150)) {  return false;  }  if((rectangle.x + rectangle.w) > (200 + 100)) {  return false;  }  if ((rectangle.y + rectangle.h) > (150 + 100)) {  return false;  }  return true;  }"}
```
this is for getting `sections` which are completely inside bounding box(x:200, y:150, w:100, h: 100). we just pass this stringified form of `js` function definition to filter corresponding to `$where` key, along with in any other filters. we can access current object being tested with `this` inside fn definition

**Comment by shashikiranraifox** [comment]
> @shashikiranraifox we can pass a js function string, with which we want to filter those rectangle anna. like, now filter_doc will be:
> 
> ```
> {"$where":"function() {  if(!this.selector || !this.selector.default || !this.selector.default.rectangle) {  return false;  }  let rectangle = this.selector.default.rectangle;  if((rectangle.x < 200) || (rectangle.y < 150)) {  return false;  }  if((rectangle.x + rectangle.w) > (200 + 100)) {  return false;  }  if ((rectangle.y + rectangle.h) > (150 + 100)) {  return false;  }  return true;  }"}
> ```
> this is for getting `sections` which are completely inside bounding box(x:200, y:150, w:100, h: 100). we just pass this stringified form of `js` function definition to filter corresponding to `$where` key, along with in any other filters. we can access current object being tested with `this` inside fn definition

What i understand is the following:
- As we are receiving Annotation List from Server and as it is already being displayed in annotations tab.
- We can filter from this list only by checking if annotations fall withing the bounding rectangle of the Sequence Annotation to be created.

I shall write the filter method myself as I have taken up the story today. However if any other set is missing apart from the above two points, please feel free to specify,



-

**Comment by damooo** [comment]
that is on client side anna. above comment is about getting them from server side itself after getting filtered, as previous requirement. above one is selector_doc **to api**, with `$where` key containing a js function in stringified form as the value,

**Comment by shashikiranraifox** [comment]
> that is on client side anna. above comment is about getting them from server side itself after getting filtered, as previous requirement. above one is selector_doc **to api**, with `$where` key containing a js function in stringified form as the value,

So if I pass the below string/json as selector_doc value, will i get the shape annotations within the bounding rectangle ?

**{"$where":"function() {  if(!this.selector || !this.selector.default || !this.selector.default.rectangle) {  return false;  }  let rectangle = this.selector.default.rectangle;  if((rectangle.x < 200) || (rectangle.y < 150)) {  return false;  }  if((rectangle.x + rectangle.w) > (200 + 100)) {  return false;  }  if ((rectangle.y + rectangle.h) > (150 + 100)) {  return false;  }  return true;  }"}**

Is the API ready or by when the API will be ready ?

**Comment by damooo** [comment]
yes anna. api is ready in v1.0, but may be somewhat slow, as server has to run `js` over each shortlisted object.
we can generate above function string, by using following example js helper fn, for custom bounding xywh:
```js
function getBoundCheckFunctionString(x, y, w, h) {
	let fn =function() {
		if(!this.selector || !this.selector.default || !this.selector.default.rectangle) {
			return false;
		}
		let rectangle = this.selector.default.rectangle;
		if((rectangle.x < X_VAL) || (rectangle.y < Y_VAL)) {
			return false;
		}
		if((rectangle.x + rectangle.w) > (X_VAL + W_VAL)) {
			return false;
		}
		if ((rectangle.y + rectangle.h) > (Y_VAL + H_VAL)) {
			return false;
		}
		return true;
	}
	return String(fn).replace(/X_VAL/g, x).replace(/Y_VAL/g, y).replace(/W_VAL/g, w).replace(/H_VAL/g, h).replace(/\t+/g, ' ').replace(/\n+/g, ' ');
}
```
and can use it like:
```js
let fn_string = getBoundCheckFunctionString(123, 45, 29, 67);
let selector_doc = JSON.stringify({"$where": fn_string});
```
we can customize logic as we want.
but this filtering will succeed only on sections created using vvadapter after pullmerge https://github.com/vedavaapi/vedavaapi-mirador/pull/4 . as that will add rectangle parameter to oa:FragmentSelector for these type of purposes.

**Comment by damooo** [comment]
should be used with other filters, like `target`, `source`, `jsonClass`, etc.

**Comment by shashikiranraifox** [comment]
Noted. Will revert after the results.

**Comment by shashikiranraifox** [comment]
@damooo I would like to use /trees GET to get all the Sequence Annotations of  page. So far I know that I have to supply  root_node_id and max_depth of a page.  I have two queries:

- if i have to fetch only SequenceAnnotations on the page which filter should I set.

- If i do not want to fetch only sequence annotations and instead want to extract from list of all annotations fetched from /trees GET response, which attribute should I use to differentiate between Normal Shape Annotation and SequenceAnnotation. Is the attribute under sections -> annotations -> content -> jsonClass. For a Normal Annotation this would be TextAnnotation, for Sequence Annotation this would be SequenceAnnotation. Please confirm?

- /trees GET does not have a selector_doc field. In it's absence which filter should i use to pass JS fn string where clause.

**Comment by shashikiranraifox** [comment]
Few more queries:

- can the response for GET /trees and GET /resources be the same when fetching list of annotations.

- How can i specify max depth using GET /resources

**Comment by shashikiranraifox** [comment]
@damooo  As per your Call today, I am specifying  the information I need:

1. Sample Request JSON to create a SequenceAnnotation.
2. /trees GET response that contains a Sequence Annotation.
3. Mention Which part of Response gives the dimension to draw a Sequence Annotation
4. Mention which part of Response gives the text of each of the member annotations of the Sequence Annotation.

The Following would be a nice feature to have:

Is there a way to Just Specify the Sequence Annotation boundary and automatically Server will put member annotations under this Sequence Annotation. Does this Server API support this kind of functionality. If there are plans to support it do let me know.

**Comment by damooo** [comment]
### 1.
first we have to create a `SpecificResource` analogous to rectangle. it is what, that is in the `on` attribute of mirador's default annotation.
```json
{
  "jsonClass": "SpecificResource",
  "type": "oa:SpecificResource",
  "purpose": "aggregation",
  "source": "5c52357042b93b40d5bb9cee",
  "selector": {
    "jsonClass": "FragmentSelector",
    "type": "oa:FragmentSelector",
    "value": "xywh=244,173,141,38",
    "conformsTo": "http://www.w3.org/TR/media-frags/",
    "rectangle": {
      "h": 38,
      "w": 141,
      "x": 244,
      "y": 173,
      "jsonClass": "WrapperObject",
      "type": "owl:Thing"
    }
  }
}
```
then a sequence annotation over that rectangle. it's `target` should be `_id` of above `SpecificResource`, representing rectangle, which this annotation is targetting. as above object still not has `_id`, below annotation will not have `target` field.
```json
{
  "jsonClass": "SequenceAnnotation",
  "type": "oa:Annotation",
  "body": {
    "jsonClass": "WrapperObject",
    "type": "owl:Thing",
    "members": {
      "0": "5c5d0ec542b93b25127d3883/5c5d0ec542b93b25127d3884",
      "1": "5c5d109542b93b25127d3885/5c5d109542b93b25127d3886",
      "jsonClass": "WrapperObject",
      "type": "owl:Thing"
    },
    "aggrContentGenerator": {
      "jsonClass": "WrapperObject",
      "type": "owl:Thing",
      "delimiter": "\n"
    },
    "orderingName": "top_to_bottom right_to_left",
    "aggregateContent": {
      "jsonClass": "Text",
      "type": "dctypes:Text",
      "chars": "<p>p.</p>\n<p>n.</p>",
      "language": "te"
    }
  }
}

```

to `POST`, these both, method will be, `i) ` `POST` first `SpecificResource` object, then get it's `_id`. `ii) ` then attach that returned `SpecificResource`'s `_id` as `target` field in above `SequenceAnnotation` object. thus we effectively `POST` both of them.

as above procedure is taking 2 `POST` requests, as `SequenceAnnotation` has to `target` `SpecificResource`, we can use `/trees` `POST` to do it in single request. i.e, in tree, we preserve, that targetting association in tree structure(will be replaced by graph api, eventually). server will take care of that association. this is what vvendpoint is doing, for postiong normal annotations from mirador. i.e, it takes mirador `single` annotation object, where rectangle details are embedded in annotation itself, and marshal it into tree form, and post it, and marshal back response into mirador's embedded format, to display on mirador. tree structure is there in vvendpoint.

### 2.
same as we getting normal annotations in vvendpoint

### 3.
same as normal annotations, we get it from `SpecificResource` object corresponding to `rectangle/shape`, to which `SequenceAnnotation` is targetting.

#### 4.
`body.aggregateContent`, if we attach the same at the time of `POST` ing.


presently, `objstore` api is only for generic resources management, with out any special treatment to content or type of resources, while following vv object model, and permission model. other services, like `smaps` use this api, and provide `domain` specific higher level functionality. for this image analytic service, presently `image analytics` service api is getting ready, which will provide these all higher level functionality regarding image analysis, like auto segmentation, and complex image dimension specific querying, etc.

presently there is a `SequenceAnnotation` created on previous page. but it's text is not displayed, as we have to give our special treatment to display of that.

**Comment by shashikiranraifox** [comment]
@damooo  The effecient way is to create a Sequence Annotation in a Single POST request. Can you please post a Sample JSON for creating a SequenceAnnotation using /trees POST request.

**Comment by shashikiranraifox** [comment]
Also let me know what filtering should be applied to GET only Sequence Annotations using a GET /trees request. Has it got to do anything with jsonClass ?

**Comment by damooo** [comment]
above `selector` is only a `FragmentSelector`. it is good if it is a `SelectorChoice` object, as like normal shape definitions, as that will allow any shape, with svgs.

**Comment by shashikiranraifox** [comment]
> above `selector` is only a `FragmentSelector`. it is good if it is a `SelectorChoice` object, as like normal shape definitions, as that will allow any shape, with svgs.

For a Sequence Annotation, only rectangle shapes are supported.  Within Sequence annotation the member annotations can be of any shapes. Will the above shared Sample JSON suffice this requirement, Please confirm.

Also if we have to get only Sequence Annotations, If i use {"jsonClass": "SequenceAnnotation"} for root_node_projection that will get me only Sequence Annotations right? Please confirm?

**Comment by damooo** [comment]
though it suffices anna, but mirador automatically converts it to `oa:Choice` type selector. so it will be good, if we provide `SpecificResource`'s `selector` in same format. like:
```json
{
  "jsonClass": "SpecificResource",
  "type": "oa:SpecificResource",
  "purpose": "aggregation",
  "source": "5c52357042b93b40d5bb9cee",
  "selector": {
    "default": {
      "value": "xywh=236,163,158,52",
      "jsonClass": "FragmentSelector",
      "type": "oa:FragmentSelector",
      "rectangle": {
        "jsonClass": "WrapperObject",
        "x": 236,
        "y": 163,
        "w": 158,
        "h": 52
      }
    },
    "item": {
      "value": "<svg xmlns='http://www.w3.org/2000/svg'><path xmlns=\"http://www.w3.org/2000/svg\" d=\"M236.02868,163.41738h78.79671v0h78.79671v25.9858v25.9858h-78.79671h-78.79671v-25.9858z\" data-paper-data=\"{&quot;strokeWidth&quot;:1,&quot;rotation&quot;:0,&quot;deleteIcon&quot;:null,&quot;rotationIcon&quot;:null,&quot;group&quot;:null,&quot;editable&quot;:true,&quot;annotation&quot;:null}\" id=\"rectangle_5a0242e7-61af-45c7-bc65-3016809bb418\" fill-opacity=\"0.00001\" fill=\"#00bfff\" fill-rule=\"nonzero\" stroke=\"#00bfff\" stroke-width=\"1\" stroke-linecap=\"butt\" stroke-linejoin=\"miter\" stroke-miterlimit=\"10\" stroke-dasharray=\"\" stroke-dashoffset=\"0\" font-family=\"none\" font-weight=\"none\" font-size=\"none\" text-anchor=\"none\" style=\"mix-blend-mode: normal\"/></svg>",
      "jsonClass": "SvgSelector",
      "type": "oa:SvgSelector"
    },
    "jsonClass": "SelectorChoice",
    "type": "oa:Choice"
  }
}
```

that should be for field `annotations_filter`, which filters which annotations to be sent, whereas `projection` only configures which fields to be sent for each corresponding resource.
