### ISSUE TITLE
[Blocker] All Users are shown in Root Admin Team. Mismatch in teams Response / members API response

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#21]
1. Login as Root Admin
2.  Add a User.
Expected result: The User should be added but should not be part of root admins team
Actual Result: The user is also part of the Root admins team when we fetch the group users through the following API:

Request URL:
https://apps.vedavaapi.org/dev/api/accounts/v1/teams/ROOT_ADMINS_TEAM/members

Response:
[
    "5cee7f94256c38000a15b8ba",
    "5cee3574256c380009d2a97c",
    "5cee6db1256c38000a15b8b9",
    "5cee8354256c38000a15b8bb"
]
https://apps.vedavaapi.org/dev/api/accounts/v1/teams?selector_doc=%7B%22members%22:%20%225cee3574256c380009d2a97c%22%7D&sort_doc=%5B%5B%22created%22,%20-1%5D%5D&start=0&count=15

In Actual there are only 3 users in the root admins group. Please check the response for the API call below

{
    "count": 15,
    "items": [
        {
            "_id": "5cee8321256c380009d2b7a0",
            "contributor": [
                "5cee3574256c380009d2a97c"
            ],
            "created": "2019-05-29 13:03:29.335514",
            "creator": "5cee3574256c380009d2a97c",
            "jsonClass": "UsersTeam",
            "members": [
                "5cee3574256c380009d2a97c",
                "5cee8354256c38000a15b8bb",
                "5cee7f94256c38000a15b8ba"
            ],
            "name": "Child of Non Root team",
            "resolvedPermissions": {
                "createAnnos": true,
                "createChildren": true,
                "delete": true,
                "jsonClass": "ResolvedPermissions",
                "read": true,
                "updateContent": true,
                "updateLinks": true,
                "updatePermissions": true
            },
            "source": "5cee4417256c38000a15b794",
            "type": "foaf:Agent"
        },
        {
            "_id": "5cee4417256c38000a15b794",
            "contributor": [
                "5cee3574256c380009d2a97c"
            ],
            "created": "2019-05-29 08:34:31.110902",
            "creator": "5cee3574256c380009d2a97c",
            "jsonClass": "UsersTeam",
            "members": [
                "5cee3574256c380009d2a97c",
                "5cee6db1256c38000a15b8b9",
                "5cee7f94256c38000a15b8ba"
            ],
            "name": "Child of Root Admin Team 2",
            "resolvedPermissions": {
                "createAnnos": true,
                "createChildren": true,
                "delete": true,
                "jsonClass": "ResolvedPermissions",
                "read": true,
                "updateContent": true,
                "updateLinks": true,
                "updatePermissions": true
            },
            "source": "ROOT_ADMINS_TEAM",
            "type": "foaf:Agent"
        },
        {
            "_id": "5cee4401256c380009d2a97d",
            "contributor": [
                "5cee3574256c380009d2a97c"
            ],
            "created": "2019-05-29 08:34:09.510545",
            "creator": "5cee3574256c380009d2a97c",
            "jsonClass": "UsersTeam",
            "members": [
                "5cee3574256c380009d2a97c"
            ],
            "name": "Child of Root admin Team",
            "resolvedPermissions": {
                "createAnnos": true,
                "createChildren": true,
                "delete": true,
                "jsonClass": "ResolvedPermissions",
                "read": true,
                "updateContent": true,
                "updateLinks": true,
                "updatePermissions": true
            },
            "source": "ROOT_ADMINS_TEAM",
            "type": "foaf:Agent"
        },
        {
            "_id": "ROOT_ADMINS_TEAM",
            "created": "2019-05-29 07:31:59.461138",
            "description": "Vedavaapi Root Admins Team",
            "jsonClass": "UsersTeam",
            "members": [
                "5cee3574256c380009d2a97c",
                "5cee6db1256c38000a15b8b9",
                "5cee8354256c38000a15b8bb"
            ],
            "name": "vedavaapi.root.admins",
            "resolvedPermissions": {
                "createAnnos": false,
                "createChildren": true,
                "delete": false,
                "jsonClass": "ResolvedPermissions",
                "read": true,
                "updateContent": true,
                "updateLinks": false,
                "updatePermissions": true
            },
            "source": "ALL_USERS_TEAM",
            "type": "foaf:Agent"
        }
    ],
    "selector_doc": {
        "jsonClass": "UsersTeam",
        "members": "5cee3574256c380009d2a97c"
    },
    "total_count": 4
}

**Comment by damooo** [comment]
Anna,
`group_json['members']` contains it's explicit members. final resolved members will be these explicit members + all it's sub teams' resolved members.
i.e. one creates a team; if `sub` team is created from that, that implicitly implies members of that sub team will also be members of that team.
there may be a `music interest team`, and `vocal interest team` is created as it's sub team, then all members of `vocal interest team` are members of `music interest team`.
in above case `Child of Non Root team` is sub team of `Child of Root Admin Team 2` which intern sub team of `ROOT_ADMINS_TEAM` . hence these two teams' members will be members of `ROOT_ADMINS_TEAM` after resolution. `/members` api gives that resolved members

**Comment by shashikiranraifox** [comment]
@damooo  Th Hierarchy has changed but these changes were not done in the Web client when the API was updated.

Can you Please provide a Different API for getting explicit members of Team ?

**Comment by damooo** [comment]
a team's key `members` contains explicit members of that team anna; and `/members` api retrieves resolved members.

**Comment by shashikiranraifox** [comment]
The other option is the following:

I use the API GET /accounts/v1/users  combining with filter $in[members array is passed] on _id to get  the users of team. 

Is there a Filter to get members of only a single team. ?

Please provide us a new filter as stated above or a new API to get only the explicit members of a team something like:

https://apps.vedavaapi.org/dev/api/accounts/v1/teams/ROOT_ADMINS_TEAM/explicit_members

**Comment by shashikiranraifox** [comment]
> a team's key `members` contains explicit members of that team anna; and `/members` api retrieves resolved members.

Not efficient to pass data around from components in client. Please provide a new API as requested above.

**Comment by damooo** [comment]
there is `only_explicit_members` url_param for that in `/members` api, if we want throgh api anna.
we can check at https://apps.vedavaapi.org/dev/api/accounts/v1/docs

**Comment by shashikiranraifox** [comment]
> there is `only_explicit_members` url_param for that in `/members` api, if we want throgh api anna.
> we can check at https://apps.vedavaapi.org/dev/api/accounts/v1/docs

This param suffices. Will try and revert

**Comment by shashikiranraifox** [comment]
The Parameter only_explicit_members  sufficed for our needs. Closing this issue.
