### ISSUE TITLE
[Blocker] All users are given all permissions on a Library by default

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#22]
1. Login as Root Admin
2. Create a New Library
3. Login again as a Normal User
4. Click on Libraries option
The Normal User can also see the newly created library. Not only that but all permissions are given by default to the User on the Library

Server URL: https://apps.vedavaapi.org/dev/api
API: GET /resources 
Request URL: 
https://apps.vedavaapi.org/dev/api/objstore/v1/resources?selector_doc=%7B%22jsonClass%22:%20%22Library%22%7D&sort_doc=%5B%5B%22created%22,%20-1%5D%5D&start=0&count=15

Response: 

{
    "count": 15,
    "items": [
        {
            "_id": "5cef9bdc256c38000a15c153",
            "contributor": [
                "5cee3574256c380009d2a97c"
            ],
            "created": "2019-05-30 09:01:16.573138",
            "creator": "5cee3574256c380009d2a97c",
            "description": "Library Should not be seen by non root users",
            "jsonClass": "Library",
            "name": "Not for Non-Root Users",
            "resolvedPermissions": {
                "createAnnos": true,
                "createChildren": true,
                "delete": true,
                "jsonClass": "ResolvedPermissions",
                "read": true,
                "updateContent": true,
                "updateLinks": true,
                "updatePermissions": true
            },
            "source": "0",
            "type": "oa:SpecificResource"
        },
        {
            "_id": "5cee7ecd256c380009d2b79e",
            "contributor": [
                "5cee3574256c380009d2a97c"
            ],
            "created": "2019-05-29 12:45:01.872154",
            "creator": "5cee3574256c380009d2a97c",
            "description": "Child of Non Root",
            "jsonClass": "Library",
            "name": "Child of Non Root Library",
            "resolvedPermissions": {
                "createAnnos": true,
                "createChildren": true,
                "delete": true,
                "jsonClass": "ResolvedPermissions",
                "read": true,
                "updateContent": true,
                "updateLinks": true,
                "updatePermissions": true
            },
            "source": "5cee6525256c38000a15b8b8",
            "type": "oa:SpecificResource"
        },
        {
            "_id": "5cee6525256c38000a15b8b8",
            "contributor": [
                "5cee3574256c380009d2a97c"
            ],
            "created": "2019-05-29 10:55:33.395702",
            "creator": "5cee3574256c380009d2a97c",
            "description": "Test Description",
            "jsonClass": "Library",
            "name": "Child of Root 1",
            "resolvedPermissions": {
                "createAnnos": true,
                "createChildren": true,
                "delete": true,
                "jsonClass": "ResolvedPermissions",
                "read": true,
                "updateContent": true,
                "updateLinks": true,
                "updatePermissions": true
            },
            "source": "0",
            "type": "oa:SpecificResource"
        },
        {
            "_id": "0",
            "jsonClass": "Library",
            "name": "root library",
            "resolvedPermissions": {
                "createAnnos": true,
                "createChildren": true,
                "delete": false,
                "jsonClass": "ResolvedPermissions",
                "read": true,
                "updateContent": true,
                "updateLinks": false,
                "updatePermissions": true
            },
            "source": null
        }
    ],
    "selector_doc": {
        "jsonClass": "Library"
    },
    "total_count": 4
}

**Comment by damooo** [comment]
may be he is member of `ROOT_ADMINS_TEAM` anna as discussed in #21

**Comment by shashikiranraifox** [comment]
> may be he is member of `ROOT_ADMINS_TEAM` anna as discussed in #21

No, One of the users is not a member of Root Admins team. 
Root Admin team members key contains the following 3 Users:

 "members": [
                "5cee3574256c380009d2a97c",
                "5cee6db1256c38000a15b8b9",
                "5cee8354256c38000a15b8bb"
            ]

5cefb662256c380009d2cb94[vvuser4@gmail.com] is a not an explicit member of root admins team.
Just revoked read and updatePermissions for this user,  still the same issue persists.

**Comment by sai-r-susarla** [comment]
The user in question seems to have been part of a subteam of root admins team. Hence he got the permissions on the library.
