### ISSUE TITLE
API to upload thumbnail for a book fails with 500 Error code

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#4]
Just noticed that the API to upload thumbnail fails. Reproducible on Swagger too. Below is the Attached Screenshot.

Note: This API was working in Server API version 0
![image](https://user-images.githubusercontent.com/45028441/52263063-34b85c80-2954-11e9-8d9c-889c51cf2989.png)

**Comment by damooo** [comment]
can you paste that _id here anna...

**Comment by damooo** [comment]
Now it is working anna. problem is storage space runned out in that partition. cleaned some.

**Comment by shashikiranraifox** [comment]
I observed the same. That it started to work now. You can close the issue.

**Comment by damooo** [comment]
there will not be problem due to this reason, as partition is changed to other one, which has lot of space.
