### ISSUE TITLE
Book Search API ?

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#7]
We would like to Implement a Book Search by title.  Right now we are using **GET /objstore/v1/resources** API to fetch list of books from  the server. Can we use this API to search for books matching a given title[either partially or fully]?

**Comment by damooo** [comment]
yes anna. it even support regex search, and filtering by some argument in many ways.

**Comment by shashikiranraifox** [comment]
Can you please let me know which request params  in this API(GET /objstore/v1/resources ) should be used for filtering using an example

**Comment by damooo** [comment]
for `selector_doc` parameter
### 1. match complete string
```json
{
 "jsonClass": "BookPortion",
  "title.chars": "1st book by Shashi Kiran"
}
```
### 2. match by regex
```json
{
  "jsonClass": "BookPortion",
  "title.chars": {
    "$regex": "^.*Kiran$"
  }
}
```
### 3. regex with custom options
below `i` is for case insensitive
```
{
  "jsonClass": "BookPortion",
  "title.chars": {
    "$regex": "^.shashi kiran$",
    "$options": "ix"
  }
}
```
above all queries give book with _id `5c528e5142b93b4c115ec9ed` as only result in present server.
we can use other options to limit, or project as we need anna.
