### ISSUE TITLE
Critical: name is User Schema is a Complex and ambigous JSON object

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#9]
I noticed that name in User Schema[under properties] is complex and ambigous. The Type could be just a string. 

**Note:** The below representation of name does not render in any form libraries.

    "name": {
      "anyOf": [
        {
          "_display": [
            "script",
            "chars",
            "language",
            "jsonClass"
          ],
          "_primary_keys": [],
          "properties": {
            "_id": {
              "description": "unique id of the object",
              "type": "string"
            },
            "chars": {
              "title": "text content",
              "type": "string"
            },
            "contributor": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "created": {
              "format": "date-time",
              "type": "string"
            },
            "creator": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              ]
            },
            "generated": {
              "format": "date-time",
              "type": "string"
            },
            "generator": {
              "type": "string"
            },
            "jsonClass": {
              "default": "Text",
              "enum": [
                "Text"
              ],
              "title": "jsonClass"
            },
            "jsonClassLabel": {
              "title": "label for json class.",
              "type": "string"
            },
            "language": {
              "enum": [
                "samskritam",
                "hindi",
                "telugu",
                "tamilam",
                "kannada",
                "malayalam",
                "paaLii",
                "english"
              ],
              "type": "string"
            },
            "metadata": {
              "items": {
                "_display": [
                  "label",
                  "value",
                  "jsonClass"
                ],
                "properties": {
                  "jsonClass": {
                    "default": "MetadataItem",
                    "enum": [
                      "MetadataItem"
                    ],
                    "title": "jsonClass"
                  },
                  "jsonClassLabel": {
                    "title": "label for json class.",
                    "type": "string"
                  },
                  "label": {
                    "type": "string"
                  },
                  "type": {
                    "enum": [
                      "sld:MetadataItem"
                    ]
                  },
                  "value": {
                    "type": [
                      "string",
                      "boolean",
                      "number",
                      "object",
                      "array"
                    ]
                  }
                },
                "required": [
                  "label",
                  "value",
                  "type",
                  "jsonClass"
                ],
                "type": "object"
              },
              "type": "array"
            },
            "modified": {
              "format": "date-time",
              "type": "string"
            },
            "permissions": {
              "allowedClasses": [
                "ObjectPermissions"
              ],
              "type": "object"
            },
            "purpose": {
              "description": "purpose of resource",
              "type": "string"
            },
            "representations": {
              "allowedClasses": [
                "DataRepresentations"
              ],
              "type": "object"
            },
            "script": {
              "enum": [
                "devanaagari",
                "paaLii",
                "braahmii",
                "grantha",
                "telugu",
                "tamilam",
                "kannada",
                "malayaalam",
                "english",
                "itrans",
                "iast"
              ],
              "type": "string"
            },
            "type": {
              "enum": [
                "dctypes:Text"
              ]
            }
          },
          "required": [
            "chars",
            "type",
            "jsonClass"
          ],
          "type": "object"
        },
        {
          "type": "string"
        },
        {
          "items": {
            "_display": [
              "script",
              "chars",
              "language",
              "jsonClass"
            ],
            "_primary_keys": [],
            "properties": {
              "_id": {
                "description": "unique id of the object",
                "type": "string"
              },
              "chars": {
                "title": "text content",
                "type": "string"
              },
              "contributor": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "created": {
                "format": "date-time",
                "type": "string"
              },
              "creator": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  }
                ]
              },
              "generated": {
                "format": "date-time",
                "type": "string"
              },
              "generator": {
                "type": "string"
              },
              "jsonClass": {
                "default": "Text",
                "enum": [
                  "Text"
                ],
                "title": "jsonClass"
              },
              "jsonClassLabel": {
                "title": "label for json class.",
                "type": "string"
              },
              "language": {
                "enum": [
                  "samskritam",
                  "hindi",
                  "telugu",
                  "tamilam",
                  "kannada",
                  "malayalam",
                  "paaLii",
                  "english"
                ],
                "type": "string"
              },
              "metadata": {
                "items": {
                  "_display": [
                    "label",
                    "value",
                    "jsonClass"
                  ],
                  "properties": {
                    "jsonClass": {
                      "default": "MetadataItem",
                      "enum": [
                        "MetadataItem"
                      ],
                      "title": "jsonClass"
                    },
                    "jsonClassLabel": {
                      "title": "label for json class.",
                      "type": "string"
                    },
                    "label": {
                      "type": "string"
                    },
                    "type": {
                      "enum": [
                        "sld:MetadataItem"
                      ]
                    },
                    "value": {
                      "type": [
                        "string",
                        "boolean",
                        "number",
                        "object",
                        "array"
                      ]
                    }
                  },
                  "required": [
                    "label",
                    "value",
                    "type",
                    "jsonClass"
                  ],
                  "type": "object"
                },
                "type": "array"
              },
              "modified": {
                "format": "date-time",
                "type": "string"
              },
              "permissions": {
                "allowedClasses": [
                  "ObjectPermissions"
                ],
                "type": "object"
              },
              "purpose": {
                "description": "purpose of resource",
                "type": "string"
              },
              "representations": {
                "allowedClasses": [
                  "DataRepresentations"
                ],
                "type": "object"
              },
              "script": {
                "enum": [
                  "devanaagari",
                  "paaLii",
                  "braahmii",
                  "grantha",
                  "telugu",
                  "tamilam",
                  "kannada",
                  "malayaalam",
                  "english",
                  "itrans",
                  "iast"
                ],
                "type": "string"
              },
              "type": {
                "enum": [
                  "dctypes:Text"
                ]
              }
            },
            "required": [
              "chars",
              "type",
              "jsonClass"
            ],
            "type": "object"
          },
          "minItems": 1,
          "type": "array"
        }
      ]
    },

**User Schema**

{
  "_display": [
    "email",
    "jsonClass",
    "agentClass",
    "name",
    "password"
  ],
  "_primary_keys": [
    [
      "email"
    ]
  ],
  "properties": {
    "_id": {
      "description": "unique id of the object",
      "type": "string"
    },
    "agentClass": {
      "enum": [
        "Software",
        "Person",
        "Team",
        "Organisation"
      ],
      "title": "agent class",
      "type": "string"
    },
    "created": {
      "format": "date-time",
      "type": "string"
    },
    "email": {
      "format": "email",
      "type": "string"
    },
    "exposed_projection": {
      "_display": [
        "jsonClass"
      ],
      "additionalProperties": {
        "enum": [
          0,
          1
        ],
        "type": "number"
      },
      "properties": {
        "jsonClass": {
          "default": "WrapperObject",
          "enum": [
            "WrapperObject"
          ],
          "title": "jsonClass"
        },
        "jsonClassLabel": {
          "title": "label for json class.",
          "type": "string"
        },
        "type": {
          "enum": [
            "owl:Thing"
          ]
        }
      },
      "required": [
        "type",
        "jsonClass"
      ],
      "type": "object"
    },
    "externalAuthentications": {
      "_display": [
        "jsonClass"
      ],
      "additionalProperties": {
        "allowedClasses": [
          "AuthenticationInfo"
        ],
        "type": "object"
      },
      "properties": {
        "jsonClass": {
          "default": "WrapperObject",
          "enum": [
            "WrapperObject"
          ],
          "title": "jsonClass"
        },
        "jsonClassLabel": {
          "title": "label for json class.",
          "type": "string"
        },
        "type": {
          "enum": [
            "owl:Thing"
          ]
        }
      },
      "required": [
        "type",
        "jsonClass"
      ],
      "type": "object"
    },
    "jsonClass": {
      "default": "User",
      "enum": [
        "User"
      ],
      "title": "jsonClass"
    },
    "jsonClassLabel": {
      "title": "label for json class.",
      "type": "string"
    },
    "modified": {
      "format": "date-time",
      "type": "string"
    },
    "name": {
      "anyOf": [
        {
          "_display": [
            "script",
            "chars",
            "language",
            "jsonClass"
          ],
          "_primary_keys": [],
          "properties": {
            "_id": {
              "description": "unique id of the object",
              "type": "string"
            },
            "chars": {
              "title": "text content",
              "type": "string"
            },
            "contributor": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "created": {
              "format": "date-time",
              "type": "string"
            },
            "creator": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              ]
            },
            "generated": {
              "format": "date-time",
              "type": "string"
            },
            "generator": {
              "type": "string"
            },
            "jsonClass": {
              "default": "Text",
              "enum": [
                "Text"
              ],
              "title": "jsonClass"
            },
            "jsonClassLabel": {
              "title": "label for json class.",
              "type": "string"
            },
            "language": {
              "enum": [
                "samskritam",
                "hindi",
                "telugu",
                "tamilam",
                "kannada",
                "malayalam",
                "paaLii",
                "english"
              ],
              "type": "string"
            },
            "metadata": {
              "items": {
                "_display": [
                  "label",
                  "value",
                  "jsonClass"
                ],
                "properties": {
                  "jsonClass": {
                    "default": "MetadataItem",
                    "enum": [
                      "MetadataItem"
                    ],
                    "title": "jsonClass"
                  },
                  "jsonClassLabel": {
                    "title": "label for json class.",
                    "type": "string"
                  },
                  "label": {
                    "type": "string"
                  },
                  "type": {
                    "enum": [
                      "sld:MetadataItem"
                    ]
                  },
                  "value": {
                    "type": [
                      "string",
                      "boolean",
                      "number",
                      "object",
                      "array"
                    ]
                  }
                },
                "required": [
                  "label",
                  "value",
                  "type",
                  "jsonClass"
                ],
                "type": "object"
              },
              "type": "array"
            },
            "modified": {
              "format": "date-time",
              "type": "string"
            },
            "permissions": {
              "allowedClasses": [
                "ObjectPermissions"
              ],
              "type": "object"
            },
            "purpose": {
              "description": "purpose of resource",
              "type": "string"
            },
            "representations": {
              "allowedClasses": [
                "DataRepresentations"
              ],
              "type": "object"
            },
            "script": {
              "enum": [
                "devanaagari",
                "paaLii",
                "braahmii",
                "grantha",
                "telugu",
                "tamilam",
                "kannada",
                "malayaalam",
                "english",
                "itrans",
                "iast"
              ],
              "type": "string"
            },
            "type": {
              "enum": [
                "dctypes:Text"
              ]
            }
          },
          "required": [
            "chars",
            "type",
            "jsonClass"
          ],
          "type": "object"
        },
        {
          "type": "string"
        },
        {
          "items": {
            "_display": [
              "script",
              "chars",
              "language",
              "jsonClass"
            ],
            "_primary_keys": [],
            "properties": {
              "_id": {
                "description": "unique id of the object",
                "type": "string"
              },
              "chars": {
                "title": "text content",
                "type": "string"
              },
              "contributor": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "created": {
                "format": "date-time",
                "type": "string"
              },
              "creator": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  }
                ]
              },
              "generated": {
                "format": "date-time",
                "type": "string"
              },
              "generator": {
                "type": "string"
              },
              "jsonClass": {
                "default": "Text",
                "enum": [
                  "Text"
                ],
                "title": "jsonClass"
              },
              "jsonClassLabel": {
                "title": "label for json class.",
                "type": "string"
              },
              "language": {
                "enum": [
                  "samskritam",
                  "hindi",
                  "telugu",
                  "tamilam",
                  "kannada",
                  "malayalam",
                  "paaLii",
                  "english"
                ],
                "type": "string"
              },
              "metadata": {
                "items": {
                  "_display": [
                    "label",
                    "value",
                    "jsonClass"
                  ],
                  "properties": {
                    "jsonClass": {
                      "default": "MetadataItem",
                      "enum": [
                        "MetadataItem"
                      ],
                      "title": "jsonClass"
                    },
                    "jsonClassLabel": {
                      "title": "label for json class.",
                      "type": "string"
                    },
                    "label": {
                      "type": "string"
                    },
                    "type": {
                      "enum": [
                        "sld:MetadataItem"
                      ]
                    },
                    "value": {
                      "type": [
                        "string",
                        "boolean",
                        "number",
                        "object",
                        "array"
                      ]
                    }
                  },
                  "required": [
                    "label",
                    "value",
                    "type",
                    "jsonClass"
                  ],
                  "type": "object"
                },
                "type": "array"
              },
              "modified": {
                "format": "date-time",
                "type": "string"
              },
              "permissions": {
                "allowedClasses": [
                  "ObjectPermissions"
                ],
                "type": "object"
              },
              "purpose": {
                "description": "purpose of resource",
                "type": "string"
              },
              "representations": {
                "allowedClasses": [
                  "DataRepresentations"
                ],
                "type": "object"
              },
              "script": {
                "enum": [
                  "devanaagari",
                  "paaLii",
                  "braahmii",
                  "grantha",
                  "telugu",
                  "tamilam",
                  "kannada",
                  "malayaalam",
                  "english",
                  "itrans",
                  "iast"
                ],
                "type": "string"
              },
              "type": {
                "enum": [
                  "dctypes:Text"
                ]
              }
            },
            "required": [
              "chars",
              "type",
              "jsonClass"
            ],
            "type": "object"
          },
          "minItems": 1,
          "type": "array"
        }
      ]
    },
    "password": {
      "format": "password",
      "type": "string"
    },
    "permissions": {
      "allowedClasses": [
        "ObjectPermissions"
      ],
      "type": "object"
    },
    "type": {
      "enum": [
        "foaf:Agent"
      ]
    }
  },
  "required": [
    "email",
    "type",
    "jsonClass"
  ],
  "type": "object"
}

**Comment by damooo** [comment]
yes, i mis-inherited field's from some other object, which is intended for text; i will change it to just string

**Comment by shashikiranraifox** [comment]
Please notify[tag] me when the issue is fixed. I shall have to remove a work around in the web app

**Comment by damooo** [comment]
@shashikiranraifox done.
